name: Push-to-EC2

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout the files
        uses: actions/checkout@v2

      # Step 2: Deploy files to the EC2 server
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 3: Execute remote commands on EC2
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install Apache if not already installed
            sudo apt-get -y update
            sudo apt-get install -y apache2 rsync

            # Ensure Apache is running
            sudo systemctl start apache2
            sudo systemctl enable apache2

            # Navigate to the home directory
            cd /home

            # Synchronize project files to Apache's root directory
            sudo rsync -av --delete --exclude '.git' . /var/www/html/

            # Set permissions for the deployed files
            sudo chmod -R 755 /var/www/html/

            # Restart Apache to apply any changes
            sudo systemctl restart apache2
